### ISSUE TITLE
Fix slight alignment issue with the mention icon text in "server" side bar

### ISSUE THREAD

**Issue by ryanbop** [JoshHyde9/forbiddenrice#1]
[Image](https://content.bope.cc/content/IwwDfLUFaE.png)

The slightly different font doesn't align **perfectly** _(the og discord one doesn't either)_ with the centre of the purple circle.

Fix the slight alignment issue 🤷‍♀️? Pls, I can't stop looking at it now that I've seen it.

Yours Truly,
Some nerd on the internet.

**Comment by JoshHyde9** [comment]
Fixed in [7d18659](https://github.com/JoshHyde9/forbiddenrice/commit/7d18659024f3e64f596681d2716058c3b19c3f38)]
