### ISSUE TITLE
Please ask before using significant portions of other people's code.

### ISSUE THREAD

**Issue by livelaughlemon** [JoshHyde9/forbiddenrice#2]
Hey there, came across this theme after finding others had taken significant portions of my styling. I'm the original author of Purpura, which it seems you have used as a base for your own. It would have been fine if you had done this and credited me or asked, but you didn't which is why I'm here. (A great theme who's asked me and credited me is Soon by SatanaDesigns who made a significantly different theme using the color scheme I made) I'm fine with using mostly the Purpura color scheme, but what I'm in no way fine with is the way you've copy and pasted with zero change to large parts of the interface. Please just add a link to my repo for Purpura with credit, thanks. 

https://github.com/livelaughlemon/purpura

**Comment by JoshHyde9** [comment]
Absolutely fair enough, I understand your frustration deeply, I should've before I started this and I planned to, but, I have no idea why. I had a lot planned for this but became disinterested very quickly and I have completely left the Discord modding scene.

I will be closing this issue and deleting the repo.
